-- The other 29 muster tables, generated from the LIVE source catalog on
-- mgtmqucaldkaxvxglguw rather than replayed from repo history.
--
-- Why not replay: the repo's 47 migrations are 532 KB of history including
-- fix-ups that overwrite each other, and PR #46 established that 24 of 39 files
-- differ from what was actually applied. Current state is 153 KB and exact.
--
-- Two columns had defaults of nextval() on sequences that do not exist here yet
-- (embedding_queue, onboarding_steps); both are plain surrogate keys, so they
-- are emitted as bigserial. Keys, FKs, indexes, triggers and RLS follow in
-- later migrations.

create table if not exists muster.agents (
  id bigint generated by default as identity not null,
  organization_id bigint, name varchar(80) not null, kind varchar(24) not null,
  description text, created_by_id bigint, active boolean default true not null,
  created_at timestamptz default now() not null, updated_at timestamptz default now() not null);

create table if not exists muster.api_keys (
  id bigint generated by default as identity not null,
  agent_id bigint not null, organization_id bigint, name varchar(80) not null,
  key_prefix char(12) not null, key_hash char(64) not null,
  scopes text[] default '{read}'::text[] not null, created_by_id bigint,
  last_used_at timestamptz, expires_at timestamptz, revoked_at timestamptz,
  created_at timestamptz default now() not null);

create table if not exists muster.brand_profiles (
  id bigint generated by default as identity not null,
  organization_id bigint not null, website_id bigint,
  brand_name varchar(80) not null, brand_mark varchar(4) not null,
  eyebrow varchar(80) default 'Website Assurance'::varchar not null,
  primary_color char(7) default '#36e2c9'::bpchar not null,
  accent_color char(7) default '#f5b942'::bpchar not null,
  logo_url varchar(1024), favicon_url varchar(1024), custom_domain varchar(253),
  support_email varchar(320), support_url varchar(1024),
  report_disclaimer text default 'Prepared under the MUSTER Assurance Framework by 28 Foot Systems. All rights reserved.'::text not null,
  report_signoff_name varchar(120), report_signoff_title varchar(120), welcome_message text,
  tone varchar(16) default 'executive'::varchar not null,
  locale varchar(10) default 'en-US'::varchar not null,
  hide_muster_attribution boolean default false not null, created_by_id bigint,
  created_at timestamptz default now() not null, updated_at timestamptz default now() not null,
  client_price_amount numeric(10,2), client_price_cadence varchar(16),
  client_payment_url varchar(1024), client_pricing_note text);

create table if not exists muster.change_events (
  id bigint generated by default as identity not null,
  organization_id bigint not null, website_id bigint not null, scan_id bigint not null,
  prev_scan_id bigint, kind varchar(40) not null, url varchar(2048),
  before_sha char(64), after_sha char(64), before_status integer, after_status integer,
  summary text, severity varchar(10) default 'info'::varchar not null,
  status varchar(20) default 'open'::varchar not null,
  detected_at timestamptz default now() not null);

create table if not exists muster.commercial_pricing (
  tier varchar(20) not null, stage varchar(10) not null,
  monthly_price_cents integer not null, included_client_orgs integer,
  additional_org_price_cents integer, stripe_price_id varchar(255),
  updated_at timestamptz default now() not null, maps_to_plan varchar);

create table if not exists muster.countries (
  code char(2) not null, name varchar(96) not null, has_regions boolean default false not null);

create table if not exists muster.embedding_queue (
  id bigserial not null, entity_type text not null, entity_id bigint not null,
  created_at timestamptz default now() not null, processed_at timestamptz);

create table if not exists muster.evidence_embeddings (
  id bigint not null, evidence_id bigint not null, organization_id bigint not null,
  website_id bigint not null, chunk_text text not null, chunk_index integer default 0 not null,
  embedding vector(1536) not null, created_at timestamptz default now() not null);

create table if not exists muster.feature_flag_overrides (
  id bigint generated by default as identity not null, flag_key varchar(48) not null,
  organization_id bigint, user_id bigint, enabled boolean not null, reason text,
  set_by_id bigint, expires_at timestamptz, created_at timestamptz default now() not null);

create table if not exists muster.feature_flags (
  key varchar(48) not null, name varchar(96) not null, description text not null,
  scope varchar(16) default 'organization'::varchar not null,
  default_enabled boolean default false not null, plan_minimum varchar(16),
  kill_switch boolean default false not null,
  created_at timestamptz default now() not null, updated_at timestamptz default now() not null);

create table if not exists muster.finding_embeddings (
  id bigint not null, finding_id bigint not null, organization_id bigint not null,
  website_id bigint not null, chunk_text text not null, chunk_index integer default 0 not null,
  embedding vector(1536) not null, created_at timestamptz default now() not null);

create table if not exists muster.finding_evidence (
  finding_id bigint not null, evidence_id bigint not null, scan_id bigint not null,
  created_at timestamptz default now() not null);

create table if not exists muster.findings (
  id bigint generated by default as identity not null,
  organization_id bigint not null, website_id bigint not null, rule_id text not null,
  fingerprint char(64) not null, severity varchar(16) not null,
  status varchar(16) default 'open'::varchar not null, title varchar(240) not null,
  detail text not null, page_url varchar(2048) not null, location varchar(400),
  confidence varchar(8) default 'high'::varchar not null, occurrences integer default 1 not null,
  first_seen_scan_id bigint, last_seen_scan_id bigint,
  first_seen_at timestamptz default now() not null, last_seen_at timestamptz default now() not null,
  resolved_at timestamptz, resolved_by_scan_id bigint, status_changed_by_id bigint,
  status_note text, risk_id bigint,
  created_at timestamptz default now() not null, updated_at timestamptz default now() not null);

create table if not exists muster.incidents (
  id bigint generated by default as identity not null, fingerprint text not null,
  source varchar(40) not null, severity varchar(10) not null,
  status varchar(20) default 'open'::varchar not null, affected_operation text not null,
  affected_release text, first_seen_at timestamptz default now() not null,
  last_seen_at timestamptz default now() not null, occurrence_count integer default 1 not null,
  evidence jsonb default '{}'::jsonb not null, root_cause_classification varchar(30),
  recovery_action varchar(60), recovery_result varchar(20), repair_pr_url text,
  closure_evidence jsonb, claimed_by text, claimed_at timestamptz,
  created_at timestamptz default now() not null, updated_at timestamptz default now() not null);

create table if not exists muster.jurisdiction_laws (
  id bigint generated by default as identity not null, jurisdiction_code varchar(8) not null,
  short_name varchar(64) not null, full_name varchar(200) not null, category varchar(24) not null,
  applies_when text not null, summary text not null, obligations jsonb default '[]'::jsonb not null,
  rule_ids text[] default '{}'::text[] not null, effective_date date,
  reference_url varchar(512), reviewed_at date not null);

create table if not exists muster.jurisdictions (
  code varchar(8) not null, kind varchar(16) not null, name varchar(96) not null,
  parent_code varchar(8), country_code char(2), advisory text not null,
  reviewed_at date not null, updated_at timestamptz default now() not null);

create table if not exists muster.notification_outbox (
  id bigint generated by default as identity not null, organization_id bigint not null,
  category varchar(30) not null, entity_type varchar(20) not null, entity_id bigint not null,
  severity varchar(10) not null, subject text not null, body_text text not null,
  recipient_emails text[] not null, status varchar(12) default 'pending'::varchar not null,
  attempts integer default 0 not null, last_error text,
  created_at timestamptz default now() not null, sent_at timestamptz);

create table if not exists muster.onboarding_steps (
  id bigserial not null, organization_id bigint not null, step_no integer not null,
  step_key varchar not null, title text not null, payload jsonb,
  completed_at timestamptz, completed_by_id bigint,
  created_at timestamptz default now() not null);

create table if not exists muster.pending_commercial_grants (
  id bigint generated by default as identity not null, email varchar(320) not null,
  plan varchar not null, stage varchar(10) not null, stripe_customer_id text,
  stripe_subscription_id text, created_at timestamptz default now() not null,
  applied_at timestamptz);

create table if not exists muster.pending_invites (
  id bigint generated by default as identity not null, organization_id bigint not null,
  email varchar(320) not null, role varchar(32) not null, invited_by_id bigint,
  created_at timestamptz default now() not null, claimed_at timestamptz);

create table if not exists muster.plans (
  plan varchar(16) not null, rank integer not null, name varchar(64) not null,
  website_limit integer not null, scan_cadence_min_minutes integer not null,
  description text not null);

create table if not exists muster.pricing_settings (
  id boolean default true not null, current_stage varchar(10) not null,
  updated_at timestamptz default now() not null);

create table if not exists muster.scan_evidence (
  id bigint generated by default as identity not null, scan_id bigint not null,
  organization_id bigint not null, website_id bigint not null, kind varchar(32) not null,
  url varchar(2048) not null, http_status integer, content_type varchar(160),
  response_ms integer, headers jsonb, excerpt text, byte_length integer, sha256 char(64),
  captured_at timestamptz default now() not null, created_at timestamptz default now() not null);

create table if not exists muster.scan_postprocess (
  scan_id bigint not null, drift_done_at timestamptz, triage_done_at timestamptz);

create table if not exists muster.scan_rules (
  rule_id text not null, category varchar(32) not null, title varchar(200) not null,
  description text not null, default_severity varchar(16) not null,
  check_type varchar(16) default 'http_native'::varchar not null,
  framework_refs jsonb default '{}'::jsonb not null, remediation text not null,
  plain_english text not null, active boolean default true not null,
  created_at timestamptz default now() not null, updated_at timestamptz default now() not null);

create table if not exists muster.scans (
  id bigint generated by default as identity not null, organization_id bigint not null,
  website_id bigint not null, trigger varchar(16) default 'manual'::varchar not null,
  status varchar(16) default 'queued'::varchar not null, requested_by_id bigint,
  requested_by_agent_id bigint, target_url varchar(1024) not null, final_url varchar(1024),
  http_status integer, response_ms integer, engine_version varchar(32),
  summary jsonb default '{}'::jsonb not null, error_message text,
  queued_at timestamptz default now() not null, started_at timestamptz, finished_at timestamptz,
  created_at timestamptz default now() not null, updated_at timestamptz default now() not null);

create table if not exists muster.sitreps (
  id bigint generated by default as identity not null, organization_id bigint not null,
  website_id bigint not null, scan_id bigint not null, version integer default 1 not null,
  status varchar(16) default 'final'::varchar not null,
  generator varchar(32) default 'deterministic-v1'::varchar not null,
  posture_score integer not null, posture_band varchar(8) not null, headline varchar(300) not null,
  sections jsonb not null, citations jsonb not null, content_md text not null,
  content_sha256 char(64) not null, generated_at timestamptz default now() not null,
  created_at timestamptz default now() not null);

create table if not exists muster.user_preferences (
  user_id bigint not null, theme varchar(8) default 'system'::varchar not null,
  density varchar(12) default 'comfortable'::varchar not null, default_organization_id bigint,
  default_view varchar(32) default 'executive'::varchar not null,
  digest_cadence varchar(8) default 'weekly'::varchar not null,
  notify_channel varchar(12) default 'email'::varchar not null, telegram_chat_id varchar(32),
  preferred_name varchar(80), updated_at timestamptz default now() not null);

create table if not exists muster.website_scan_settings (
  website_id bigint not null, enabled boolean default true not null,
  cadence_minutes integer default 1440 not null, next_run_at timestamptz default now() not null,
  last_run_at timestamptz, max_pages integer default 1 not null,
  created_at timestamptz default now() not null, updated_at timestamptz default now() not null);
