-- Check constraints for the 29 generated tables, from pg_get_constraintdef on
-- the live source. These carry real product rules (severity ladders, incident
-- taxonomy, posture score bounds, the ai_governance category added later), so
-- they are copied from what is enforced rather than from the repo.

alter table muster.agents add constraint agents_kind_check check (((kind)::text = any ((array['internal_employee'::character varying, 'customer_agent'::character varying, 'integration'::character varying])::text[])));
alter table muster.brand_profiles add constraint brand_profiles_accent_color_check check ((accent_color ~ '^#[0-9a-fA-F]{6}$'::text));
alter table muster.brand_profiles add constraint brand_profiles_client_price_amount_check check (((client_price_amount is null) or (client_price_amount >= (0)::numeric)));
alter table muster.brand_profiles add constraint brand_profiles_client_price_cadence_check check (((client_price_cadence is null) or ((client_price_cadence)::text = any ((array['monthly'::character varying, 'annual'::character varying, 'one_time'::character varying, 'custom'::character varying])::text[]))));
alter table muster.brand_profiles add constraint brand_profiles_primary_color_check check ((primary_color ~ '^#[0-9a-fA-F]{6}$'::text));
alter table muster.brand_profiles add constraint brand_profiles_tone_check check (((tone)::text = any ((array['executive'::character varying, 'plain'::character varying, 'technical'::character varying])::text[])));
alter table muster.change_events add constraint change_events_status_check check (((status)::text = any ((array['open'::character varying, 'reviewed'::character varying, 'ignored'::character varying])::text[])));
alter table muster.commercial_pricing add constraint commercial_pricing_additional_org_price_cents_check check (((additional_org_price_cents is null) or (additional_org_price_cents >= 0)));
alter table muster.commercial_pricing add constraint commercial_pricing_monthly_price_cents_check check ((monthly_price_cents >= 0));
alter table muster.commercial_pricing add constraint commercial_pricing_stage_check check (((stage)::text = any ((array['seed'::character varying, 'fruit'::character varying])::text[])));
alter table muster.commercial_pricing add constraint commercial_pricing_tier_check check (((tier)::text = any ((array['muster'::character varying, 'muster_partner'::character varying])::text[])));
alter table muster.embedding_queue add constraint embedding_queue_entity_type_check check ((entity_type = any (array['finding'::text, 'evidence'::text])));
alter table muster.feature_flag_overrides add constraint feature_flag_overrides_check check (((organization_id is not null) or (user_id is not null)));
alter table muster.feature_flags add constraint feature_flags_scope_check check (((scope)::text = any ((array['platform'::character varying, 'organization'::character varying, 'user'::character varying])::text[])));
alter table muster.findings add constraint findings_confidence_check check (((confidence)::text = any ((array['high'::character varying, 'medium'::character varying, 'low'::character varying])::text[])));
alter table muster.findings add constraint findings_severity_check check (((severity)::text = any ((array['critical'::character varying, 'high'::character varying, 'medium'::character varying, 'low'::character varying, 'info'::character varying])::text[])));
alter table muster.findings add constraint findings_status_check check (((status)::text = any ((array['open'::character varying, 'reopened'::character varying, 'resolved'::character varying, 'accepted'::character varying, 'false_positive'::character varying])::text[])));
alter table muster.incidents add constraint incidents_recovery_result_check check (((recovery_result)::text = any ((array['recovered'::character varying, 'failed'::character varying, 'not_applicable'::character varying])::text[])));
alter table muster.incidents add constraint incidents_root_cause_classification_check check (((root_cause_classification)::text = any ((array['expected_validation'::character varying, 'user_misunderstanding'::character varying, 'ux_defect'::character varying, 'permission_denial'::character varying, 'expired_connection'::character varying, 'bad_configuration'::character varying, 'external_outage'::character varying, 'quota_limit'::character varying, 'data_drift'::character varying, 'race_condition'::character varying, 'regression'::character varying, 'code_defect'::character varying, 'security_incident'::character varying, 'unresolved'::character varying])::text[])));
alter table muster.incidents add constraint incidents_severity_check check (((severity)::text = any ((array['info'::character varying, 'warning'::character varying, 'critical'::character varying])::text[])));
alter table muster.incidents add constraint incidents_source_check check (((source)::text = any ((array['cron_failure'::character varying, 'cron_missed'::character varying, 'scan_stuck'::character varying, 'scan_silent_failure'::character varying, 'alert_dead_letter'::character varying, 'commercial_grant_stuck'::character varying, 'engine_error_spike'::character varying, 'manual'::character varying])::text[])));
alter table muster.incidents add constraint incidents_status_check check (((status)::text = any ((array['open'::character varying, 'investigating'::character varying, 'recovered'::character varying, 'patch_pending'::character varying, 'patch_verified'::character varying, 'awaiting_release'::character varying, 'deployed_awaiting_observation'::character varying, 'closed'::character varying, 'wont_fix'::character varying])::text[])));
alter table muster.jurisdiction_laws add constraint jurisdiction_laws_category_check check (((category)::text = any (array['privacy'::text, 'accessibility'::text, 'security'::text, 'marketing'::text, 'breach'::text, 'consumer'::text, 'sector'::text, 'ai_governance'::text])));
alter table muster.jurisdictions add constraint jurisdictions_kind_check check (((kind)::text = any ((array['supranational'::character varying, 'country'::character varying, 'region'::character varying])::text[])));
alter table muster.notification_outbox add constraint notification_outbox_category_check check (((category)::text = 'risk_opened'::text));
alter table muster.notification_outbox add constraint notification_outbox_entity_type_check check (((entity_type)::text = 'risk'::text));
alter table muster.notification_outbox add constraint notification_outbox_severity_check check (((severity)::text = any ((array['critical'::character varying, 'high'::character varying])::text[])));
alter table muster.notification_outbox add constraint notification_outbox_status_check check (((status)::text = any ((array['pending'::character varying, 'sending'::character varying, 'sent'::character varying, 'failed'::character varying, 'skipped'::character varying])::text[])));
alter table muster.pending_commercial_grants add constraint pending_commercial_grants_stage_check check (((stage)::text = any ((array['seed'::character varying, 'fruit'::character varying])::text[])));
alter table muster.pending_invites add constraint pending_invites_role_check check (((role)::text = any ((array['executive'::character varying, 'risk_owner'::character varying, 'control_owner'::character varying, 'contributor'::character varying, 'viewer'::character varying])::text[])));
alter table muster.pricing_settings add constraint pricing_settings_current_stage_check check (((current_stage)::text = any ((array['seed'::character varying, 'fruit'::character varying])::text[])));
alter table muster.pricing_settings add constraint pricing_settings_id_check check (id);
alter table muster.scan_evidence add constraint scan_evidence_kind_check check (((kind)::text = any ((array['http_response'::character varying, 'redirect_chain'::character varying, 'robots_txt'::character varying, 'sitemap'::character varying, 'security_txt'::character varying, 'http_probe'::character varying, 'html_excerpt'::character varying, 'header_set'::character varying])::text[])));
alter table muster.scan_rules add constraint scan_rules_category_check check (((category)::text = any (array['security'::text, 'privacy'::text, 'accessibility'::text, 'availability'::text, 'third_party'::text, 'governance'::text, 'ai_governance'::text])));
alter table muster.scan_rules add constraint scan_rules_check_type_check check (((check_type)::text = any ((array['http_native'::character varying, 'browser'::character varying, 'manual'::character varying])::text[])));
alter table muster.scan_rules add constraint scan_rules_default_severity_check check (((default_severity)::text = any ((array['critical'::character varying, 'high'::character varying, 'medium'::character varying, 'low'::character varying, 'info'::character varying])::text[])));
alter table muster.scans add constraint scans_status_check check (((status)::text = any ((array['queued'::character varying, 'running'::character varying, 'complete'::character varying, 'failed'::character varying])::text[])));
alter table muster.scans add constraint scans_trigger_check check (((trigger)::text = any ((array['scheduled'::character varying, 'manual'::character varying, 'api'::character varying, 'onboarding'::character varying])::text[])));
alter table muster.sitreps add constraint sitreps_posture_band_check check (((posture_band)::text = any ((array['green'::character varying, 'amber'::character varying, 'red'::character varying])::text[])));
alter table muster.sitreps add constraint sitreps_posture_score_check check (((posture_score >= 0) and (posture_score <= 100)));
alter table muster.sitreps add constraint sitreps_status_check check (((status)::text = any ((array['draft'::character varying, 'final'::character varying, 'superseded'::character varying])::text[])));
alter table muster.user_preferences add constraint user_preferences_density_check check (((density)::text = any ((array['comfortable'::character varying, 'compact'::character varying])::text[])));
alter table muster.user_preferences add constraint user_preferences_digest_cadence_check check (((digest_cadence)::text = any ((array['off'::character varying, 'daily'::character varying, 'weekly'::character varying])::text[])));
alter table muster.user_preferences add constraint user_preferences_notify_channel_check check (((notify_channel)::text = any ((array['email'::character varying, 'telegram'::character varying, 'none'::character varying])::text[])));
alter table muster.user_preferences add constraint user_preferences_theme_check check (((theme)::text = any ((array['system'::character varying, 'dark'::character varying, 'light'::character varying])::text[])));
alter table muster.website_scan_settings add constraint website_scan_settings_cadence_minutes_check check ((cadence_minutes >= 60));
alter table muster.website_scan_settings add constraint website_scan_settings_max_pages_check check (((max_pages >= 1) and (max_pages <= 25)));
