-- Renames the internal `muster` schema to `cavscope`, per explicit instruction
-- overriding the "muster stays the internal codename" decision recorded in
-- CLAUDE.md. Scope is deliberately narrow: the SCHEMA namespace only.
--
-- public.muster_* RPC shim names, muster-* edge function slugs, the
-- muster.partners/*.muster.28footsystems.com hostnames, the x-muster-secret
-- header, mk_ key prefixes, and muster_* internal identifier/column-naming
-- conventions (vault secret names, pricing tier values, actor-name strings,
-- verification-token prefixes) are OUT of scope and are deliberately left
-- untouched -- verified empirically against a throwaway probe schema before
-- this ran, not assumed:
--
--   - RLS policies, CHECK constraints, and column DEFAULTs that reference
--     muster.* are stored as OID-bound expression trees, not text -- Postgres
--     deparses them fresh from the catalog every time, so all 53 policies,
--     2 check constraints, and 23 sequence-backed column defaults resolve to
--     cavscope.* automatically the instant the schema is renamed. Confirmed
--     directly: created zzz_rename_probe with a function, a table, a CHECK
--     constraint calling it, an RLS policy referencing it, and a
--     nextval()::regclass column default, renamed the schema twice, and
--     every one of those definitions re-rendered under the new name with
--     zero edits, then dropped the probe schema. Same reason foreign keys
--     were never a concern -- OID, not name, is the real reference.
--   - Function and procedure BODIES are the opposite: plpgsql/sql bodies are
--     stored as literal text (pg_proc.prosrc) and are never pre-parsed into
--     an OID-bound tree, so a literal `muster.foo(...)` call or a
--     `SET search_path TO 'muster', ...` clause inside a body does NOT
--     follow the rename -- it errors the next time the function runs,
--     because the schema it names no longer exists. Every function/procedure
--     definition across `muster`+`public` containing such a literal
--     reference is recreated below via CREATE OR REPLACE, generated from its
--     own current definition (a two-part substitution: a regex for
--     schema-qualified `muster.` refs, protected so it never touches the
--     muster.partners hostname or a muster.28footsystems one; plus exact
--     literal replacement of the six SET search_path clause shapes
--     pg_get_functiondef actually emits -- a generic bare-word pass was
--     proven unsafe in dry-run: it silently rewrote a commercial pricing
--     tier value ('muster' as data, compared against 'muster_partner') in
--     muster_admin_set_pricing_visibility and muster_public_pricing, and was
--     dropped for that reason).
--   - pg_cron job commands are also literal text in a regular table column
--     (cron.job.command), not a parsed expression -- jobid 7 calls
--     `muster.autotriage()` directly and needed the same fix.
--
-- Verified live after applying: cavscope schema holds the same 54 tables and
-- 80 functions muster held; zero remaining schema-qualified `muster.`
-- references anywhere in cavscope+public (the hostname excepted); RLS policy
-- count (83) and trigger count (39) unchanged from before the migration;
-- public.muster_plans() and public.muster_public_pricing() both executed
-- successfully end to end afterward, and the pricing-tier data values
-- ('muster', 'muster_partner' as data, not schema) came back unchanged.
--
-- Deployed edge function source was checked and needs NO change: none of the
-- 11 files that mention "muster" call `.schema('muster')` or otherwise touch
-- the internal schema directly -- every occurrence is either a call to an
-- unchanged public.muster_*/muster_engine_* RPC shim by name, or a comment.
-- Those comments now describe the schema by its old name; that is stale
-- prose, not a functional gap, and was left for a separate cleanup pass.
--
-- NOTE ON REPO/DATABASE DRIFT: at the time this ran, the live project already
-- carried seven migrations with no corresponding file anywhere in this
-- repository's git history (muster_sitrep_ready_email,
-- muster_sitrep_ready_org_preference_and_ui_rpcs,
-- muster_notification_category_registry_and_lifecycle_events,
-- muster_fix_reintroduced_doubled_backslash_regex,
-- muster_autotriage_risk_opened_cavscope_branding,
-- muster_default_brand_and_report_copy_cavscope_branding,
-- muster_customer_facing_copy_cavscope_branding -- versions 20260926010259
-- through 20260926032118). This migration was generated by re-scanning
-- pg_proc/cron.job fresh at execution time, so it is correct regardless of
-- what those seven migrations changed -- but their own SQL is not recorded
-- anywhere in version control and could not be reconstructed after the fact
-- without guessing. Reconciling that gap is a separate, outstanding task.

alter schema muster rename to cavscope;

do $$
declare
  r record;
  new_def text;
  n_changed int := 0;
begin
  for r in
    select p.oid, pg_get_functiondef(p.oid) as def
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname in ('cavscope', 'public') and p.prokind in ('f', 'p')
  loop
    new_def := regexp_replace(r.def, 'muster\.(?!partners|28footsystems)', 'cavscope.', 'g');
    new_def := replace(new_def, $sp$SET search_path TO 'muster', 'public', 'pg_temp'$sp$, $sp$SET search_path TO 'cavscope', 'public', 'pg_temp'$sp$);
    new_def := replace(new_def, $sp$SET search_path TO 'public', 'muster', 'pg_temp'$sp$, $sp$SET search_path TO 'public', 'cavscope', 'pg_temp'$sp$);
    new_def := replace(new_def, $sp$SET search_path TO 'muster', 'public'$sp$, $sp$SET search_path TO 'cavscope', 'public'$sp$);
    new_def := replace(new_def, $sp$SET search_path TO 'public', 'muster'$sp$, $sp$SET search_path TO 'public', 'cavscope'$sp$);
    new_def := replace(new_def, $sp$SET search_path TO 'muster', 'pg_temp'$sp$, $sp$SET search_path TO 'cavscope', 'pg_temp'$sp$);
    new_def := replace(new_def, $sp$SET search_path TO 'muster'$sp$, $sp$SET search_path TO 'cavscope'$sp$);

    if new_def is distinct from r.def then
      execute new_def;
      n_changed := n_changed + 1;
    end if;
  end loop;

  if n_changed < 150 then
    raise exception 'only % function/procedure definitions changed, expected at least 150. Aborting so this migration fails loudly rather than silently doing less than verified.', n_changed;
  end if;

  raise notice 'recreated % function/procedure definitions', n_changed;
end $$;

-- The one pg_cron job that calls into the schema directly (the other four
-- go over HTTP to edge functions and never touch the schema name at all).
select cron.alter_job(
  (select jobid from cron.job where command like '%muster.autotriage%'),
  command := 'select cavscope.autotriage();'
);

-- Fails loudly rather than leaving a silent gap: after the two textual fixes
-- above, and given RLS/constraints/defaults auto-resolve, nothing anywhere
-- in cavscope+public should still contain a schema-qualified `muster.` ref
-- (the hostname excepted) or a stale search_path literal.
do $$
declare
  n int;
begin
  select count(*) into n
  from pg_proc p
  join pg_namespace n2 on n2.oid = p.pronamespace
  where n2.nspname in ('cavscope', 'public') and p.prokind in ('f', 'p')
    and (
      pg_get_functiondef(p.oid) ~ 'muster\.(?!partners|28footsystems)'
      or pg_get_functiondef(p.oid) like '%search_path TO ''muster''%'
      or pg_get_functiondef(p.oid) like '%''muster'', ''public''%'
      or pg_get_functiondef(p.oid) like '%''public'', ''muster''%'
    );
  if n <> 0 then
    raise exception '% function/procedure definition(s) still carry a stale muster schema reference after the fix pass.', n;
  end if;

  if exists (select 1 from cron.job where command like '%muster.autotriage%') then
    raise exception 'cron job still calls muster.autotriage() directly.';
  end if;

  if not exists (select 1 from pg_namespace where nspname = 'cavscope') then
    raise exception 'cavscope schema does not exist after rename.';
  end if;
  if exists (select 1 from pg_namespace where nspname = 'muster') then
    raise exception 'muster schema still exists after rename.';
  end if;
end $$;
