-- muster_047: MUSTER's own documentation, retrievable by the agent.
--
-- The agent could already search findings (what is wrong with a site) and evidence
-- (what the scanner captured). It could not search the one thing that explains what
-- any of it MEANS -- the rule catalog, the email routing model, the impersonation
-- protocol. So an agent asked "what does EMAIL-003 actually cost us" had the finding
-- text and nothing else, and the gap between "has the finding" and "can explain the
-- finding" is where a model starts composing.
--
-- Two design decisions worth stating, because both are the kind that look arbitrary
-- later:
--
-- 1. VISIBILITY IS NOT COSMETIC. docs/ is not uniformly publishable. SCAN-RULES.md
--    is exactly what a client's agent should be able to quote. CUTOVER.md, EMAIL.md,
--    IMPERSONATION.md, BACKEND.md and MAGIC-LINK.md describe internal infrastructure:
--    project refs, RPC names, which gates exist and where. Making all of docs/
--    searchable by any tenant key would be an information-disclosure change dressed
--    up as a retrieval feature. Every chunk carries a visibility, the search defaults
--    to 'public' only, and 'internal' requires a platform-scoped admin key.
--
-- 2. NO IVFFLAT INDEX, ON PURPOSE. findings and evidence carry one, because they grow
--    without bound. docs/ is a few hundred chunks. An ivfflat index with lists=100
--    over ~300 rows puts ~3 rows in each list and probes one list per query, so it
--    would silently return a near-empty result set and look like "the docs aren't
--    embedded yet". A sequential scan over a few hundred 1536-dim vectors is fast and
--    exact. Add the index when the corpus justifies it, and set lists from the real
--    row count when you do.

create table if not exists muster.doc_chunks (
  id           bigint generated by default as identity primary key,
  doc_path     text not null,
  doc_title    text not null,
  visibility   text not null default 'internal',
  heading      text not null,
  -- GitHub-style slug, so a citation is a link a human can open rather than a
  -- reference they have to go hunting for.
  anchor       text not null,
  chunk_index  integer not null,
  chunk_text   text not null,
  -- sha256 of chunk_text. The sync tool sends hashes first so unchanged sections
  -- are never re-embedded: re-running the sync on an untouched docs/ costs nothing.
  content_sha  char(64) not null,
  embedding    public.vector(1536) not null,
  token_estimate integer,
  updated_at   timestamptz not null default now(),
  constraint doc_chunks_visibility_check check (visibility in ('public', 'internal')),
  constraint doc_chunks_scope_unique unique (doc_path, chunk_index)
);

create index if not exists idx_doc_chunks_path on muster.doc_chunks using btree (doc_path);
create index if not exists idx_doc_chunks_visibility on muster.doc_chunks using btree (visibility);

-- No tenant owns these rows, and no tenant reads them directly. The only read path
-- is the SECURITY DEFINER shim below, so RLS is on with no permissive select policy:
-- if this table is ever reachable through PostgREST by accident, it returns nothing.
alter table muster.doc_chunks enable row level security;

create or replace function muster.q_search_docs(
  p_query_embedding public.vector,
  p_limit integer default 8,
  p_threshold double precision default 0.5,
  p_include_internal boolean default false
) returns table(
  doc_path text, doc_title text, heading text, anchor text,
  visibility text, chunk_text text, similarity double precision
) language sql stable
set search_path to 'public', 'muster'
as $function$
  select d.doc_path, d.doc_title, d.heading, d.anchor, d.visibility, d.chunk_text,
         (1 - pow(d.embedding <-> p_query_embedding, 2) / 4)::float as similarity
  from muster.doc_chunks d
  where (coalesce(p_include_internal, false) or d.visibility = 'public')
    and (1 - pow(d.embedding <-> p_query_embedding, 2) / 4)::float >= coalesce(p_threshold, 0.5)
  order by similarity desc
  limit greatest(1, least(coalesce(p_limit, 8), 25));
$function$;

create or replace function public.muster_engine_search_docs(
  p_ctx jsonb,
  p_embedding public.vector,
  p_limit integer default 8,
  p_threshold double precision default 0.5
) returns jsonb
language plpgsql
security definer
set search_path to 'public', 'muster', 'pg_temp'
as $function$
declare
  v_scopes text[] := array(select jsonb_array_elements_text(coalesce(p_ctx->'scopes', '[]'::jsonb)));
  v_key_org bigint := nullif(p_ctx->>'organization_id', '')::bigint;
  v_internal boolean;
begin
  if not ('admin' = any (v_scopes) or 'read' = any (v_scopes)) then
    raise exception 'key lacks the read scope' using errcode = '42501';
  end if;

  -- Internal documentation is reachable only by a platform-scoped admin key
  -- (organization_id null AND the admin scope). A tenant key with admin scope is
  -- an admin of ONE organization; that does not make MUSTER's own infrastructure
  -- notes theirs to read.
  v_internal := (v_key_org is null and 'admin' = any (v_scopes));

  return coalesce(
    jsonb_agg(jsonb_build_object(
      'doc_path', r.doc_path,
      'doc_title', r.doc_title,
      'heading', r.heading,
      'anchor', r.anchor,
      'visibility', r.visibility,
      'chunk_text', r.chunk_text,
      'similarity', r.similarity
    ) order by r.similarity desc),
    '[]'::jsonb
  ) from muster.q_search_docs(p_embedding, p_limit, p_threshold, v_internal) r;
end;
$function$;

-- Same posture as the other retrieval wrappers: anon and authenticated must not be
-- able to POST /rest/v1/rpc/muster_engine_search_docs. The edge function calls it
-- with the service role, which carries its own ctx built from a verified API key.
revoke execute on function public.muster_engine_search_docs(jsonb, public.vector, integer, double precision) from public, anon, authenticated;
grant execute on function public.muster_engine_search_docs(jsonb, public.vector, integer, double precision) to service_role;

-- Upsert one chunk. Called by muster-embed-docs once per changed section; unchanged
-- sections never reach it, because the sync compares hashes first.
create or replace function public.muster_engine_upsert_doc_chunk(
  p_doc_path text, p_doc_title text, p_visibility text, p_heading text, p_anchor text,
  p_chunk_index integer, p_chunk_text text, p_content_sha text, p_embedding public.vector,
  p_token_estimate integer default null
) returns bigint
language plpgsql
security definer
set search_path to 'public', 'muster', 'pg_temp'
as $function$
declare v_id bigint;
begin
  if p_visibility not in ('public', 'internal') then
    raise exception 'visibility must be public or internal, got %', p_visibility using errcode = '22023';
  end if;
  insert into muster.doc_chunks
    (doc_path, doc_title, visibility, heading, anchor, chunk_index, chunk_text, content_sha, embedding, token_estimate)
  values
    (p_doc_path, p_doc_title, p_visibility, p_heading, p_anchor, p_chunk_index, p_chunk_text, p_content_sha, p_embedding, p_token_estimate)
  on conflict (doc_path, chunk_index) do update set
    doc_title = excluded.doc_title, visibility = excluded.visibility,
    heading = excluded.heading, anchor = excluded.anchor,
    chunk_text = excluded.chunk_text, content_sha = excluded.content_sha,
    embedding = excluded.embedding, token_estimate = excluded.token_estimate,
    updated_at = now()
  returning id into v_id;
  return v_id;
end;
$function$;

-- What the sync needs before deciding what to embed: the hashes already stored for
-- one document. Returning hashes rather than text keeps the round trip small and
-- keeps the decision ("has this section changed") on one side.
create or replace function public.muster_engine_doc_chunk_hashes(p_doc_path text)
returns jsonb
language sql
security definer
set search_path to 'public', 'muster', 'pg_temp'
as $function$
  select coalesce(jsonb_object_agg(d.chunk_index::text, jsonb_build_object(
           'sha', d.content_sha, 'visibility', d.visibility, 'heading', d.heading)), '{}'::jsonb)
  from muster.doc_chunks d where d.doc_path = p_doc_path;
$function$;

-- Drop sections that no longer exist in the file. Without this, deleting a heading
-- from a doc leaves its text searchable forever, and the agent cites guidance that
-- was removed on purpose -- the worst kind of stale, because it still reads current.
create or replace function public.muster_engine_prune_doc_chunks(p_doc_path text, p_keep integer[])
returns integer
language plpgsql
security definer
set search_path to 'public', 'muster', 'pg_temp'
as $function$
declare v_deleted integer;
begin
  delete from muster.doc_chunks d
  where d.doc_path = p_doc_path
    and not (d.chunk_index = any (coalesce(p_keep, '{}'::integer[])));
  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$function$;

revoke execute on function public.muster_engine_upsert_doc_chunk(text, text, text, text, text, integer, text, text, public.vector, integer) from public, anon, authenticated;
revoke execute on function public.muster_engine_doc_chunk_hashes(text) from public, anon, authenticated;
revoke execute on function public.muster_engine_prune_doc_chunks(text, integer[]) from public, anon, authenticated;
grant execute on function public.muster_engine_upsert_doc_chunk(text, text, text, text, text, integer, text, text, public.vector, integer) to service_role;
grant execute on function public.muster_engine_doc_chunk_hashes(text) to service_role;
grant execute on function public.muster_engine_prune_doc_chunks(text, integer[]) to service_role;

-- Assert the posture rather than trust it: a later migration that recreates one of
-- these wrappers without the revoke would otherwise reopen the hole silently.
do $$
declare v_bad text;
begin
  select string_agg(p.proname, ', ') into v_bad
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and p.proname in ('muster_engine_search_docs','muster_engine_upsert_doc_chunk',
                      'muster_engine_doc_chunk_hashes','muster_engine_prune_doc_chunks')
    and (has_function_privilege('anon', p.oid, 'execute')
      or has_function_privilege('authenticated', p.oid, 'execute'));
  if v_bad is not null then
    raise exception 'doc retrieval wrappers reachable by anon/authenticated: %', v_bad;
  end if;
end $$;
