-- Repairs 36 of 79 CHECK constraints and 3 partial indexes that muster_007 and
-- muster_009 got wrong. Every one of them dropped allowed values.
--
-- This was invisible to the earlier verification because that verification
-- counted objects (79 checks, 122 indexes) instead of comparing their
-- definitions. Counting proves nothing about content. It surfaced only when
-- real data hit the constraints: muster.users row 3 (the super_admin) was
-- rejected because users_role_check here permitted only 'user' and 'admin'.
--
-- Every structural object type is now compared by md5 of its definition, not
-- by count. Columns, primary keys, unique constraints and foreign keys already
-- matched on that basis; these two did not.
alter table muster.agents drop constraint if exists agents_kind_check; alter table muster.agents add constraint agents_kind_check CHECK (((kind)::text = ANY ((ARRAY['internal_employee'::character varying, 'customer_agent'::character varying, 'integration'::character varying])::text[])));
alter table muster.brand_profiles drop constraint if exists brand_profiles_client_price_cadence_check; alter table muster.brand_profiles add constraint brand_profiles_client_price_cadence_check CHECK (((client_price_cadence IS NULL) OR ((client_price_cadence)::text = ANY ((ARRAY['monthly'::character varying, 'annual'::character varying, 'one_time'::character varying, 'custom'::character varying])::text[]))));
alter table muster.brand_profiles drop constraint if exists brand_profiles_tone_check; alter table muster.brand_profiles add constraint brand_profiles_tone_check CHECK (((tone)::text = ANY ((ARRAY['executive'::character varying, 'plain'::character varying, 'technical'::character varying])::text[])));
alter table muster.change_events drop constraint if exists change_events_status_check; alter table muster.change_events add constraint change_events_status_check CHECK (((status)::text = ANY ((ARRAY['open'::character varying, 'reviewed'::character varying, 'ignored'::character varying])::text[])));
alter table muster.commercial_pricing drop constraint if exists commercial_pricing_stage_check; alter table muster.commercial_pricing add constraint commercial_pricing_stage_check CHECK (((stage)::text = ANY ((ARRAY['seed'::character varying, 'fruit'::character varying])::text[])));
alter table muster.commercial_pricing drop constraint if exists commercial_pricing_tier_check; alter table muster.commercial_pricing add constraint commercial_pricing_tier_check CHECK (((tier)::text = ANY ((ARRAY['muster'::character varying, 'muster_partner'::character varying])::text[])));
alter table muster.feature_flags drop constraint if exists feature_flags_scope_check; alter table muster.feature_flags add constraint feature_flags_scope_check CHECK (((scope)::text = ANY ((ARRAY['platform'::character varying, 'organization'::character varying, 'user'::character varying])::text[])));
alter table muster.findings drop constraint if exists findings_confidence_check; alter table muster.findings add constraint findings_confidence_check CHECK (((confidence)::text = ANY ((ARRAY['high'::character varying, 'medium'::character varying, 'low'::character varying])::text[])));
alter table muster.findings drop constraint if exists findings_severity_check; alter table muster.findings add constraint findings_severity_check CHECK (((severity)::text = ANY ((ARRAY['critical'::character varying, 'high'::character varying, 'medium'::character varying, 'low'::character varying, 'info'::character varying])::text[])));
alter table muster.findings drop constraint if exists findings_status_check; alter table muster.findings add constraint findings_status_check CHECK (((status)::text = ANY ((ARRAY['open'::character varying, 'reopened'::character varying, 'resolved'::character varying, 'accepted'::character varying, 'false_positive'::character varying])::text[])));
alter table muster.incidents drop constraint if exists incidents_recovery_result_check; alter table muster.incidents add constraint incidents_recovery_result_check CHECK (((recovery_result)::text = ANY ((ARRAY['recovered'::character varying, 'failed'::character varying, 'not_applicable'::character varying])::text[])));
alter table muster.incidents drop constraint if exists incidents_root_cause_classification_check; alter table muster.incidents add constraint incidents_root_cause_classification_check CHECK (((root_cause_classification)::text = ANY ((ARRAY['expected_validation'::character varying, 'user_misunderstanding'::character varying, 'ux_defect'::character varying, 'permission_denial'::character varying, 'expired_connection'::character varying, 'bad_configuration'::character varying, 'external_outage'::character varying, 'quota_limit'::character varying, 'data_drift'::character varying, 'race_condition'::character varying, 'regression'::character varying, 'code_defect'::character varying, 'security_incident'::character varying, 'unresolved'::character varying])::text[])));
alter table muster.incidents drop constraint if exists incidents_severity_check; alter table muster.incidents add constraint incidents_severity_check CHECK (((severity)::text = ANY ((ARRAY['info'::character varying, 'warning'::character varying, 'critical'::character varying])::text[])));
alter table muster.incidents drop constraint if exists incidents_source_check; alter table muster.incidents add constraint incidents_source_check CHECK (((source)::text = ANY ((ARRAY['cron_failure'::character varying, 'cron_missed'::character varying, 'scan_stuck'::character varying, 'scan_silent_failure'::character varying, 'alert_dead_letter'::character varying, 'commercial_grant_stuck'::character varying, 'engine_error_spike'::character varying, 'manual'::character varying])::text[])));
alter table muster.incidents drop constraint if exists incidents_status_check; alter table muster.incidents add constraint incidents_status_check CHECK (((status)::text = ANY ((ARRAY['open'::character varying, 'investigating'::character varying, 'recovered'::character varying, 'patch_pending'::character varying, 'patch_verified'::character varying, 'awaiting_release'::character varying, 'deployed_awaiting_observation'::character varying, 'closed'::character varying, 'wont_fix'::character varying])::text[])));
alter table muster.jurisdictions drop constraint if exists jurisdictions_kind_check; alter table muster.jurisdictions add constraint jurisdictions_kind_check CHECK (((kind)::text = ANY ((ARRAY['supranational'::character varying, 'country'::character varying, 'region'::character varying])::text[])));
alter table muster.notification_outbox drop constraint if exists notification_outbox_severity_check; alter table muster.notification_outbox add constraint notification_outbox_severity_check CHECK (((severity)::text = ANY ((ARRAY['critical'::character varying, 'high'::character varying])::text[])));
alter table muster.notification_outbox drop constraint if exists notification_outbox_status_check; alter table muster.notification_outbox add constraint notification_outbox_status_check CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'sending'::character varying, 'sent'::character varying, 'failed'::character varying, 'skipped'::character varying])::text[])));
alter table muster.organizations drop constraint if exists organizations_commercial_stage_check; alter table muster.organizations add constraint organizations_commercial_stage_check CHECK (((commercial_stage)::text = ANY ((ARRAY['seed'::character varying, 'fruit'::character varying])::text[])));
alter table muster.organizations drop constraint if exists organizations_onboarding_check; alter table muster.organizations add constraint organizations_onboarding_check CHECK (((onboarding_status)::text = ANY ((ARRAY['started'::character varying, 'profile'::character varying, 'website'::character varying, 'first_scan'::character varying, 'complete'::character varying])::text[])));
alter table muster.organizations drop constraint if exists organizations_plan_check; alter table muster.organizations add constraint organizations_plan_check CHECK (((plan)::text = ANY ((ARRAY['trial'::character varying, 'starter'::character varying, 'pro'::character varying, 'enterprise'::character varying, 'internal'::character varying])::text[])));
alter table muster.pending_commercial_grants drop constraint if exists pending_commercial_grants_stage_check; alter table muster.pending_commercial_grants add constraint pending_commercial_grants_stage_check CHECK (((stage)::text = ANY ((ARRAY['seed'::character varying, 'fruit'::character varying])::text[])));
alter table muster.pending_invites drop constraint if exists pending_invites_role_check; alter table muster.pending_invites add constraint pending_invites_role_check CHECK (((role)::text = ANY ((ARRAY['executive'::character varying, 'risk_owner'::character varying, 'control_owner'::character varying, 'contributor'::character varying, 'viewer'::character varying])::text[])));
alter table muster.pricing_settings drop constraint if exists pricing_settings_current_stage_check; alter table muster.pricing_settings add constraint pricing_settings_current_stage_check CHECK (((current_stage)::text = ANY ((ARRAY['seed'::character varying, 'fruit'::character varying])::text[])));
alter table muster.scan_evidence drop constraint if exists scan_evidence_kind_check; alter table muster.scan_evidence add constraint scan_evidence_kind_check CHECK (((kind)::text = ANY ((ARRAY['http_response'::character varying, 'redirect_chain'::character varying, 'robots_txt'::character varying, 'sitemap'::character varying, 'security_txt'::character varying, 'http_probe'::character varying, 'html_excerpt'::character varying, 'header_set'::character varying])::text[])));
alter table muster.scan_rules drop constraint if exists scan_rules_check_type_check; alter table muster.scan_rules add constraint scan_rules_check_type_check CHECK (((check_type)::text = ANY ((ARRAY['http_native'::character varying, 'browser'::character varying, 'manual'::character varying])::text[])));
alter table muster.scan_rules drop constraint if exists scan_rules_default_severity_check; alter table muster.scan_rules add constraint scan_rules_default_severity_check CHECK (((default_severity)::text = ANY ((ARRAY['critical'::character varying, 'high'::character varying, 'medium'::character varying, 'low'::character varying, 'info'::character varying])::text[])));
alter table muster.scans drop constraint if exists scans_status_check; alter table muster.scans add constraint scans_status_check CHECK (((status)::text = ANY ((ARRAY['queued'::character varying, 'running'::character varying, 'complete'::character varying, 'failed'::character varying])::text[])));
alter table muster.scans drop constraint if exists scans_trigger_check; alter table muster.scans add constraint scans_trigger_check CHECK (((trigger)::text = ANY ((ARRAY['scheduled'::character varying, 'manual'::character varying, 'api'::character varying, 'onboarding'::character varying])::text[])));
alter table muster.sitreps drop constraint if exists sitreps_posture_band_check; alter table muster.sitreps add constraint sitreps_posture_band_check CHECK (((posture_band)::text = ANY ((ARRAY['green'::character varying, 'amber'::character varying, 'red'::character varying])::text[])));
alter table muster.sitreps drop constraint if exists sitreps_status_check; alter table muster.sitreps add constraint sitreps_status_check CHECK (((status)::text = ANY ((ARRAY['draft'::character varying, 'final'::character varying, 'superseded'::character varying])::text[])));
alter table muster.user_preferences drop constraint if exists user_preferences_density_check; alter table muster.user_preferences add constraint user_preferences_density_check CHECK (((density)::text = ANY ((ARRAY['comfortable'::character varying, 'compact'::character varying])::text[])));
alter table muster.user_preferences drop constraint if exists user_preferences_digest_cadence_check; alter table muster.user_preferences add constraint user_preferences_digest_cadence_check CHECK (((digest_cadence)::text = ANY ((ARRAY['off'::character varying, 'daily'::character varying, 'weekly'::character varying])::text[])));
alter table muster.user_preferences drop constraint if exists user_preferences_notify_channel_check; alter table muster.user_preferences add constraint user_preferences_notify_channel_check CHECK (((notify_channel)::text = ANY ((ARRAY['email'::character varying, 'telegram'::character varying, 'none'::character varying])::text[])));
alter table muster.user_preferences drop constraint if exists user_preferences_theme_check; alter table muster.user_preferences add constraint user_preferences_theme_check CHECK (((theme)::text = ANY ((ARRAY['system'::character varying, 'dark'::character varying, 'light'::character varying])::text[])));
alter table muster.users drop constraint if exists users_role_check; alter table muster.users add constraint users_role_check CHECK (((role)::text = ANY ((ARRAY['user'::character varying, 'admin'::character varying, 'super_admin'::character varying])::text[])));

drop index if exists muster.incidents_fingerprint_active;
drop index if exists muster.incidents_status;
drop index if exists muster.scans_active_idx;
CREATE UNIQUE INDEX incidents_fingerprint_active ON muster.incidents USING btree (fingerprint) WHERE ((status)::text <> ALL ((ARRAY['closed'::character varying, 'wont_fix'::character varying])::text[]));
CREATE INDEX incidents_status ON muster.incidents USING btree (status) WHERE ((status)::text <> ALL ((ARRAY['closed'::character varying, 'wont_fix'::character varying])::text[]));
CREATE INDEX scans_active_idx ON muster.scans USING btree (status) WHERE ((status)::text = ANY ((ARRAY['queued'::character varying, 'running'::character varying])::text[]));
